services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: timetrackingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: time
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  backend:
    build: ./time-tracking-backend
    environment:
      DATABASE_NAME: timetrackingdb
      DATABASE_USER: postgres
      DATABASE_PASSWORD: time
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py makemigrations api --noinput &&
             python manage.py migrate api --noinput &&
             python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    develop:
      watch:
        - action: sync+restart
          path: ./time-tracking-backend
          target: /app
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
            - "**/*.pyo"
            - "**/*.pyd"
            - "**/.Python"
            - "**/env"
            - "**/venv"
            - "**/.env"
            - "**/.venv"

  frontend:
    build: ./time-tracking-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000/api
    develop:
      watch:
        - action: sync
          path: ./time-tracking-frontend/src
          target: /app/src
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./time-tracking-frontend/package.json

volumes:
  postgres_data:
